In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/Telco_Customer_Churn.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [4]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

### Quitar espacios innecesarios

In [5]:
df["TotalCharges"] = df["TotalCharges"].str.strip()

### Convertir string a numérico

coerce convierte los errores en NaN

In [6]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors="coerce")

### Revisar valores Nulos

In [7]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

### Eliminar valores nulos

In [8]:
df = df.dropna()

In [9]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

### Eliminar Columnas inútiles

In [10]:
df = df.drop("customerID", axis=1)

### Convertir Variables binarias a 0 y 1

In [11]:
binary_cols = [
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling",
    "Churn"
]

for col in binary_cols:
    df[col] = df[col].map({
        "Yes": 1,
        "No": 0
    })

### One-Hot encoding para categóricas

In [13]:
df = pd.get_dummies(
    df,
    drop_first=True
)

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   Partner                                7032 non-null   int64
 2   Dependents                             7032 non-null   int64
 3   tenure                                 7032 non-null   int64
 4   PhoneService                           7032 non-null   int64
 5   PaperlessBilling                       7032 non-null   int64
 6   MonthlyCharges                         7032 non-null   float64
 7   TotalCharges                           7032 non-null   float64
 8   Churn                                  7032 non-null   int64
 9   gender_Male                            7032 non-null   bool
 10  MultipleLines_No phone service         7032 non-null   bool
 11  MultipleLines_Yes                      7032 non-null   bool
 12  InternetService_Fiber optic            7032 non-null   bool
 13  InternetService_No                     7032 non-null   bool
 14  OnlineSecurity_No internet service     7032 non-null   bool
 15  OnlineSecurity_Yes                     7032 non-null   bool
 16  OnlineBackup_No internet service       7032 non-null   bool
 17  OnlineBackup_Yes                       7032 non-null   bool
 18  DeviceProtection_No internet service   7032 non-null   bool
 19  DeviceProtection_Yes                   7032 non-null   bool
 20  TechSupport_No internet service        7032 non-null   bool
 21  TechSupport_Yes                        7032 non-null   bool
 22  StreamingTV_No internet service        7032 non-null   bool
 23  StreamingTV_Yes                        7032 non-null   bool
 24  StreamingMovies_No internet service    7032 non-null   bool
 25  StreamingMovies_Yes                    7032 non-null   bool
 26  Contract_One year                      7032 non-null   bool
 27  Contract_Two year                      7032 non-null   bool
 28  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 29  PaymentMethod_Electronic check         7032 non-null   bool
 30  PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(22), float64(2), int64(7)
memory usage: 700.5 KB

In [15]:
df.head()

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,gender_Male,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,1,0,1,29.85,29.85,0,False,...,False,False,False,False,False,False,False,False,True,False
1,0,0,0,34,1,0,56.95,1889.50,0,True,...,False,False,False,False,False,True,False,False,False,True
2,0,0,0,2,1,1,53.85,108.15,1,True,...,False,False,False,False,False,False,False,False,False,True
3,0,0,0,45,0,0,42.30,1840.75,0,True,...,True,False,False,False,False,True,False,False,False,False
4,0,0,0,2,1,1,70.70,151.65,1,False,...,False,False,False,False,False,False,False,False,True,False

###